Budget.Presentation.MVC/ViewModels/ItemSubValorViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Budget.Presentation.MVC.ViewModels
{
    public class ItemSubValorViewModel
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public decimal Valor { get; set; }

        public ItemValorViewModel ItemValor { get; set; }
    }
}

Budget.Presentation.MVC/Controllers/API/ItemSubValorController.cs
using Budget.Application.Interfaces;
using Budget.Domain.Entities;
using Budget.MVC.ViewModels;
using Marisa.Ecommerce.Web;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Budget.MVC.Controllers
{
    public class ItemSubValorController : Controller
    {

        private readonly IGerenciadorDeItemSubValor _gerenciadorDeItemSubValor;

        public ItemSubValorController(IGerenciadorDeItemSubValor gerenciadorDeItemSubValor)
        {
            _gerenciadorDeItemSubValor = gerenciadorDeItemSubValor;
        }

        // GET: Orcamento
        public ActionResult Index(int id)
        {
            var itemSubValores = _gerenciadorDeItemSubValor.Listar();
            var itemSubValorViewModel = Mapeador.Mapear<IEnumerable<ItemSubValor>, IEnumerable<ItemSubValorViewModel>>(itemSubValores);

            return View(itemSubValorViewModel);
        }

        // GET: Orcamento/Details/5
        public ActionResult Details(int id)
        {
            var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
            var itemSubValorViewModel = Mapeador.Mapear<ItemSubValor, ItemSubValorViewModel>(itemSubValor);

            return View(itemSubValorViewModel);
        }

        // GET: Orcamento/Create
        public ActionResult Create()
        {
            var itemSubValorViewModel = new ItemSubValorViewModel();
            PreparaViewData(itemSubValorViewModel);
            return View();
        }

        // POST: Orcamento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemSubValorViewModel itemSubValorViewModel)
        {
            try
            {
                var itemSubValor = Mapeador.Mapear<ItemSubValorViewModel, ItemSubValor>(itemSubValorViewModel);
                _gerenciadorDeItemSubValor.Salvar(itemSubValor);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Edit/5
        public ActionResult Edit(int id)
        {
            var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
            var itemSubValorViewModel = Mapeador.Mapear<ItemSubValor, ItemSubValorViewModel>(itemSubValor);

            PreparaViewData(itemSubValorViewModel);
            return View(itemSubValorViewModel);
        }

        // POST: Orcamento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ItemSubValorViewModel itemSubValorViewModel)
        {
            try
            {
                var itemSubValor = Mapeador.Mapear<ItemSubValorViewModel, ItemSubValor>(itemSubValorViewModel);
                _gerenciadorDeItemSubValor.Editar(itemSubValor);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Delete/5
        public ActionResult Delete(int id)
        {
            var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
            var itemSubValorViewModel = Mapeador.Mapear<ItemSubValor, ItemSubValorViewModel>(itemSubValor);

            return View(itemSubValorViewModel);
        }

        // POST: Orcamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ItemSubValorViewModel itemSubValorViewModel)
        {
            try
            {
                var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
                _gerenciadorDeItemSubValor.Excluir(itemSubValor);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void PreparaViewData(ItemSubValorViewModel itemSubValorViewModel)
        {
            //ViewBag.TipoPessoa = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPessoaViewModel>(orcamentoViewModel.TipoPessoa);
            //ViewBag.TipoOrcamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoOrcamentoViewModel>(orcamentoViewModel.TipoOrcamento);
            //ViewBag.TipoPagamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPagamentoViewModel>(orcamentoViewModel.TipoPagamento);
        }
    }
}

Budget.Presentation.MVC/Controllers/ItemSubValorController.cs
using Budget.Application.Interfaces;
using Budget.Domain.Entities;
using Budget.Presentation.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;

namespace Budget.Presentation.MVC.Controllers
{
    [Authorize]
    public class ItemSubValorController : Controller
    {
        private readonly IGerenciadorDeItemSubValor _gerenciadorDeItemSubValor;
        private readonly IGerenciadorDeItemValor _gerenciadorDeItemValor;

        public ItemSubValorController(IGerenciadorDeItemSubValor gerenciadorDeItemSubValor, IGerenciadorDeItemValor gerenciadorDeItemValor)
        {
            _gerenciadorDeItemSubValor = gerenciadorDeItemSubValor;
            _gerenciadorDeItemValor = gerenciadorDeItemValor;
        }

        // GET: Orcamento
        public ActionResult Index(int id)
        {
            var itemSubValores = _gerenciadorDeItemSubValor.BuscaPorValor(id);
            var itemSubValorViewModel = Mapeador.Mapear<IEnumerable<ItemSubValor>, IEnumerable<ItemSubValorViewModel>>(itemSubValores);

            ViewBag.ItemValorId = id;
            ViewBag.OrcamentoId = (itemSubValorViewModel.Count() == 0) ? _gerenciadorDeItemValor.BuscarPorId(id).Orcamento.ID : itemSubValorViewModel.First().ItemValor.Orcamento.Id;

            return View(itemSubValorViewModel);
        }

        // GET: Orcamento/Details/5
        public ActionResult Details(int id)
        {
            var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
            var itemSubValorViewModel = Mapeador.Mapear<ItemSubValor, ItemSubValorViewModel>(itemSubValor);

            return View(itemSubValorViewModel);
        }

        // GET: Orcamento/Create
        public ActionResult Create(int id)
        {
            var itemSubValorViewModel = new ItemSubValorViewModel();
            itemSubValorViewModel.ItemValor = new ItemValorViewModel() { Id = id };
            PreparaViewData(itemSubValorViewModel);
            return View(itemSubValorViewModel);
        }

        // POST: Orcamento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemSubValorViewModel itemSubValorViewModel)
        {
            try
            {
                var itemSubValor = Mapeador.Mapear<ItemSubValorViewModel, ItemSubValor>(itemSubValorViewModel);
                _gerenciadorDeItemSubValor.Salvar(itemSubValor);

                return RedirectToAction("Index", new { id = itemSubValorViewModel.ItemValor.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Edit/5
        public ActionResult Edit(int id)
        {
            var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
            var itemSubValorViewModel = Mapeador.Mapear<ItemSubValor, ItemSubValorViewModel>(itemSubValor);

            PreparaViewData(itemSubValorViewModel);
            return View(itemSubValorViewModel);
        }

        // POST: Orcamento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ItemSubValorViewModel itemSubValorViewModel)
        {
            try
            {
                var itemSubValor = Mapeador.Mapear<ItemSubValorViewModel, ItemSubValor>(itemSubValorViewModel);
                _gerenciadorDeItemSubValor.Editar(itemSubValor);

                return RedirectToAction("Index", new { id = itemSubValorViewModel.ItemValor.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Delete/5
        public ActionResult Delete(int id)
        {
            var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
            var itemSubValorViewModel = Mapeador.Mapear<ItemSubValor, ItemSubValorViewModel>(itemSubValor);

            return View(itemSubValorViewModel);
        }

        // POST: Orcamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ItemSubValorViewModel itemSubValorViewModel)
        {
            try
            {
                var itemSubValor = _gerenciadorDeItemSubValor.BuscarPorId(id);
                _gerenciadorDeItemSubValor.Excluir(itemSubValor);

                return RedirectToAction("Index", new { id = itemSubValorViewModel.ItemValor.Id });
            }
            catch
            {
                return View();
            }
        }

        private void PreparaViewData(ItemSubValorViewModel itemSubValorViewModel)
        {
            if (itemSubValorViewModel == null)
                throw new ArgumentNullException("ItemSubValorViewModel");

            //ViewBag.TipoPessoa = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPessoaViewModel>(orcamentoViewModel.TipoPessoa);
            //ViewBag.TipoOrcamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoOrcamentoViewModel>(orcamentoViewModel.TipoOrcamento);
            //ViewBag.TipoPagamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPagamentoViewModel>(orcamentoViewModel.TipoPagamento);
        }
    }
}

Budget.Presentation.MVC/Controllers/ItemValorController.cs
using Budget.Application.Interfaces;
using Budget.Domain.Entities;
using Budget.Presentation.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Budget.Presentation.MVC.Controllers
{
    [Authorize]
    public class ItemValorController : Controller
    {
        private readonly IGerenciadorDeItemValor _gerenciadorDeItemValor;

        public ItemValorController(IGerenciadorDeItemValor gerenciadorDeItemValor)
        {
            _gerenciadorDeItemValor = gerenciadorDeItemValor;
        }

        // GET: Orcamento
        public ActionResult Index(int id)
        {
            var itemValores = _gerenciadorDeItemValor.BuscaPorOrcamento(id);
            var itemValorViewModel = Mapeador.Mapear<IEnumerable<ItemValor>, IEnumerable<ItemValorViewModel>>(itemValores);

            ViewBag.OrcamentoId = id;

            return View(itemValorViewModel);
        }

        // GET: Orcamento/Details/5
        public ActionResult Details(int id)
        {
            var itemValor = _gerenciadorDeItemValor.BuscarPorId(id);
            var itemValorViewModel = Mapeador.Mapear<ItemValor, ItemValorViewModel>(itemValor);

            return View(itemValorViewModel);
        }

        // GET: Orcamento/Create
        public ActionResult Create(int id)
        {
            var itemValorViewModel = new ItemValorViewModel();
            itemValorViewModel.Orcamento = new OrcamentoViewModel() { Id = id };
            PreparaViewData(itemValorViewModel);
            return View(itemValorViewModel);
        }

        // POST: Orcamento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemValorViewModel itemValorViewModel)
        {
            try
            {
                var itemValor = Mapeador.Mapear<ItemValorViewModel, ItemValor>(itemValorViewModel);
                _gerenciadorDeItemValor.Salvar(itemValor);

                return RedirectToAction("Index", new { id = itemValorViewModel.Orcamento.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Edit/5
        public ActionResult Edit(int id)
        {
            var itemValor = _gerenciadorDeItemValor.BuscarPorId(id);
            var itemValorViewModel = Mapeador.Mapear<ItemValor, ItemValorViewModel>(itemValor);

            PreparaViewData(itemValorViewModel);
            return View(itemValorViewModel);
        }

        // POST: Orcamento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ItemValorViewModel itemValorViewModel)
        {
            try
            {
                var itemValor = Mapeador.Mapear<ItemValorViewModel, ItemValor>(itemValorViewModel);
                _gerenciadorDeItemValor.Editar(itemValor);

                return RedirectToAction("Index", new { id = itemValorViewModel.Orcamento.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Delete/5
        public ActionResult Delete(int id)
        {
            var itemValor = _gerenciadorDeItemValor.BuscarPorId(id);
            var itemValorViewModel = Mapeador.Mapear<ItemValor, ItemValorViewModel>(itemValor);

            return View(itemValorViewModel);
        }

        // POST: Orcamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ItemValorViewModel itemValorViewModel)
        {
            try
            {
                var itemValor = _gerenciadorDeItemValor.BuscarPorId(id);
                _gerenciadorDeItemValor.Excluir(itemValor);

                return RedirectToAction("Index", new { id = itemValorViewModel.Orcamento.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Delete/5
        public ActionResult ItemSubValor(int id)
        {
            return RedirectToAction("Index", "ItemSubValor", new { id = id });
        }

        private void PreparaViewData(ItemValorViewModel itemValorViewModel)
        {
            if(itemValorViewModel == null)
                throw new ArgumentNullException("ItemValorViewModel");
            
            //ViewBag.TipoPessoa = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPessoaViewModel>(orcamentoViewModel.TipoPessoa);
            //ViewBag.TipoOrcamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoOrcamentoViewModel>(orcamentoViewModel.TipoOrcamento);
            //ViewBag.TipoPagamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPagamentoViewModel>(orcamentoViewModel.TipoPagamento);
        }
    }
}

Budget.Presentation.MVC/Views/ItemSubValor/Create.cshtml
@model Budget.Presentation.MVC.ViewModels.ItemSubValorViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ItemSubValorViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemValor.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.ItemValor.Id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budget.Presentation.MVC/Views/ItemSubValor/Delete.cshtml
@model Budget.Presentation.MVC.ViewModels.ItemSubValorViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ItemSubValorViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        
        @Html.HiddenFor(model => model.ItemValor.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { Model.ItemValor.Id })
        </div>
    }
</div>

Budget.Presentation.MVC/Views/ItemSubValor/Details.cshtml
@model Budget.Presentation.MVC.ViewModels.ItemSubValorViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ItemSubValorViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", new { Model.ItemValor.Id })
</p>

Budget.Presentation.MVC/Views/ItemSubValor/Edit.cshtml
@model Budget.Presentation.MVC.ViewModels.ItemSubValorViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ItemSubValorViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ItemValor.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { Model.ItemValor.Id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budget.Presentation.MVC/Views/ItemSubValor/Index.cshtml
@model IEnumerable<Budget.Presentation.MVC.ViewModels.ItemSubValorViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.ItemValorId })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Valor)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to Valores", "Index", "ItemValor", new { id = ViewBag.OrcamentoId }, null)
</div>