Budget.Presentation.MVC/Controllers/OrcamentoController.cs
using Budget.Application.Interfaces;
using Budget.Domain.Entities;
using Budget.Presentation.MVC.ViewModel.Enum;
using Budget.Presentation.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Budget.Presentation.MVC.Controllers
{
    [Authorize]
    public class OrcamentoController : Controller
    {
        private readonly IGerenciadorDeOrcamento _gerenciadorDeOrcamento;

        public OrcamentoController(IGerenciadorDeOrcamento gerenciadorDeOrcamento)
        {
            _gerenciadorDeOrcamento = gerenciadorDeOrcamento;
        }

        // GET: Orcamento Angular
        public ActionResult Angular()
        {
            return View();
        }

        // GET: Orcamento
        public ActionResult Index()
        {
            var orcamentos = _gerenciadorDeOrcamento.Listar();
            var orcamentoViewModel = Mapeador.Mapear<IEnumerable<Orcamento>, IEnumerable<OrcamentoViewModel>>(orcamentos);

            return View(orcamentoViewModel);
        }

        // GET: Orcamento/Details/5
        public ActionResult Details(int id)
        {
            var orcamento = _gerenciadorDeOrcamento.BuscarPorId(id);
            var orcamentoViewModel = Mapeador.Mapear<Orcamento, OrcamentoViewModel>(orcamento);

            return View(orcamentoViewModel);
        }

        // GET: Orcamento/Create
        public ActionResult Create()
        {
            var orcamentoViewModel = new OrcamentoViewModel();
            PreparaViewData(orcamentoViewModel);
            return View();
        }

        // POST: Orcamento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrcamentoViewModel orcamentoViewModel)
        {
            try
            {
                var orcamento = Mapeador.Mapear<OrcamentoViewModel, Orcamento>(orcamentoViewModel);
                _gerenciadorDeOrcamento.Salvar(orcamento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Edit/5
        public ActionResult Edit(int id)
        {
            var orcamento = _gerenciadorDeOrcamento.BuscarPorId(id);
            var orcamentoViewModel = Mapeador.Mapear<Orcamento, OrcamentoViewModel>(orcamento);

            PreparaViewData(orcamentoViewModel);
            return View(orcamentoViewModel);
        }

        // POST: Orcamento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, OrcamentoViewModel orcamentoViewModel)
        {
            try
            {
                var orcamento = Mapeador.Mapear<OrcamentoViewModel, Orcamento>(orcamentoViewModel);
                _gerenciadorDeOrcamento.Editar(orcamento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Delete/5
        public ActionResult Delete(int id)
        {
            var orcamento = _gerenciadorDeOrcamento.BuscarPorId(id);
            var orcamentoViewModel = Mapeador.Mapear<Orcamento, OrcamentoViewModel>(orcamento);

            return View(orcamentoViewModel);
        }

        // POST: Orcamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, OrcamentoViewModel orcamentoViewModel)
        {
            try
            {
                var orcamento = _gerenciadorDeOrcamento.BuscarPorId(id);
                _gerenciadorDeOrcamento.Excluir(orcamento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orcamento/Delete/5
        public ActionResult ItemValor(int id)
        {
            return RedirectToAction("Index", "ItemValor", new { id = id });
        }

        private void PreparaViewData(OrcamentoViewModel orcamentoViewModel)
        {
            if (orcamentoViewModel != null)
            {
                ViewBag.TipoPessoa = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPessoaViewModel>(orcamentoViewModel.TipoPessoa);
                ViewBag.TipoOrcamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoOrcamentoViewModel>(orcamentoViewModel.TipoOrcamento);
                ViewBag.TipoPagamento = Budget.Infrastructure.Helpers.EnumHelper.GetList<ETipoPagamentoViewModel>(orcamentoViewModel.TipoPagamento);
            }
            else
            {
                throw new ArgumentNullException("OrcamentoViewModel");
            }
        }
    }
}

Budget.Presentation.MVC/Controllers/UsuariosController.cs
using Budget.Application.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Budget.Presentation.MVC.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {

        private readonly IGerenciadorDeUsuario _gerenciadorDeUsuario;

        public UsuariosController(IGerenciadorDeUsuario gerenciadorDeUsuario)
        {
            _gerenciadorDeUsuario = gerenciadorDeUsuario;
        }

        // GET: Usuarios
        public ActionResult Index()
        {
            return View(_gerenciadorDeUsuario.ObterTodos());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(string id)
        {
            return View(_gerenciadorDeUsuario.ObterPorId(id));
        }

        public ActionResult DesativarLock(string id)
        {
            _gerenciadorDeUsuario.DesativarLock(id);
            return RedirectToAction("Index");
        }
    }
}

Budget.Presentation.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bugdet - André Raiça</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Budget", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Lista Usuários", "Index", "Usuarios")</li>
                    <li>@Html.ActionLink("Orçamento", "Index", "Orcamento")</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bugdet - André Raiça</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/angular")*@
    @RenderSection("scripts", required: false)
</body>
</html>